var id = 100;
//id="Ravi";
var fname = "Ravi Kumar";
var result = true;
var msg = "Welcome";
msg = 100;
msg = true;
var id1 = 200; //base upon value it consider as type data types. 
//id1="Ravi";
var fname1 = "Ravi Kumar";
var result1 = false;
var msg1 = 100;
msg1 = "Ravi";
var id2;
var fname2;
var result3;
var msg2;
id2 = 200;
fname2 = "Mahesh";
result3 = true;
msg2 = "Hi";
console.log(id2);
console.log(fname2);
console.log(result3);
